// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBncrU8P6Wpch12TpQZKAXadBi8fbLmPJk',
    appId: '1:434966604146:web:8423a03b97a0d0b1f395eb',
    messagingSenderId: '434966604146',
    projectId: 'my-tiktok-b56cd',
    authDomain: 'my-tiktok-b56cd.firebaseapp.com',
    storageBucket: 'my-tiktok-b56cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3bLa1xIk2kQ1wF0OY6r8zd3UWQav5xkQ',
    appId: '1:434966604146:android:0305be54e5e97eaff395eb',
    messagingSenderId: '434966604146',
    projectId: 'my-tiktok-b56cd',
    storageBucket: 'my-tiktok-b56cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-i3smw2VoVjuxJhWl8uOJRXajoCdAatA',
    appId: '1:434966604146:ios:2c2ea690654acac9f395eb',
    messagingSenderId: '434966604146',
    projectId: 'my-tiktok-b56cd',
    storageBucket: 'my-tiktok-b56cd.appspot.com',
    iosClientId: '434966604146-a3vlmhp8ts3437oonshvfcqkjffiv7bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-i3smw2VoVjuxJhWl8uOJRXajoCdAatA',
    appId: '1:434966604146:ios:2c2ea690654acac9f395eb',
    messagingSenderId: '434966604146',
    projectId: 'my-tiktok-b56cd',
    storageBucket: 'my-tiktok-b56cd.appspot.com',
    iosClientId: '434966604146-a3vlmhp8ts3437oonshvfcqkjffiv7bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
